language: python
env:
    matrix:
        - TOXENV=py33
        - TOXENV=py34
        - TOXENV=coverage
install:
    - pip install tox
    - if test "$TOXENV" = coverage; then pip install coveralls; fi
script:
    - tox
after_success:
    - if test "$TOXENV" = coverage; then coveralls; fi
notifications:
    slack:
        - secure: hqS/rzW16lC/x8nGXsRUtt3R+mSwAXngNE1hGNcjlEOq+imGpGK1Lct+HvfzeBrUNOWyqjQVZfc6IFzRN2gos+dWYxNqMojn1GkpTFF6P09HdEwjkdzcVFuUSmohcdsRmfGkVDqtQMTv9g75neiSzvpaaOhDjGN9aUBXF1zsNY8=
