language: python
python:
    - '3.3'
    - '3.4'
install:
    - pip install coveralls
script:
    - nosetests -s  --verbosity=2 --with-coverage --cover-erase=true --cover-package=py3oauth2
after_success:
    - coveralls
